var _udn, _uhash, _utimeout, _utcp;
(function(){function f(){if(!_udn||""==_udn||"none"==_udn)return _udn="",1;if("auto"==_udn){var b=document.domain;"www."==b.substring(0,4)&&(b=b.substring(4,b.length));_udn=b}if("off"==_uhash||!_udn||""==_udn)return 1;for(var a=b=0,c=_udn.length-1;0<=c;c--)if(a=parseInt(_udn.charCodeAt(c),0),b=(b<<6&268435455)+a+(a<<14),0!=(a=b&266338304))b^=a>>21;return b}function g(b,a,c){var d;d=window._gaUserPrefs;var e="ioo";d=d&&d[e]&&d[e]();d||(a=f()+"."+a,_udn&&""!=_udn&&(a+=";domain="+_udn),a+=";path="+_utcp,
0==c&&_utimeout&&""!=_utimeout&&(c=_utimeout),0<c&&(a+=";expires="+(new Date((new Date).getTime()+1E3*c)).toGMTString()),document.cookie=b+"="+a)}_udn||(_udn="auto");_uhash||(_uhash="on");_utcp||(_utcp="/");_utimeout||(_utimeout="1800");g('__utmx','',46656000);g('__utmxx','',46656000)})();
var k=!0,m=null;function utmx_section(e){return utmx("section",e)}
function utmx(e,b,i,f){function o(a,d,b){function e(a,b,d,c,f,g){function i(a,b){for(var d=a.split(b),f=[],c=0;c<d.length;c++)if(0!=d[c].length){var e=d[c].split("="),g=e[0],e=2<=e.length?e[1]:m;f.push([g,e])}return f}function p(a,b){for(var d=[],c=0;c<a.length;c++){0!=c&&d.push(b);d.push(a[c][0]);var e=a[c][1];e!=m&&(d.push("="),d.push(e))}return d.join("")}function l(a,d){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);for(c=0;c<d.length;c++){for(var e=d[c][0],f=!1,g=0;g<a.length;g++)if(e==a[g][0]){f=
k;break}f||b.push(d[c])}return b}var b=new String(b),j=b.indexOf(c);if(0<=j){var h=g?b.indexOf(g,j):-1;0>h&&(h=b.length);b=b.substring(j+1,h);h=d.indexOf(c);0>h&&(h=0);var n=g?d.indexOf(g,h):-1;0>n&&(n=d.length);j=d.substring(0,h?h:n);g=d.substring(n);a?f=b:(a=0==h?"":d.substring(h+1,n),a=l(i(a,f),i(b,f)),f=p(a,f));f&&0<f.length&&(j+=c+f);d=j+=g}return d}d||(d=0);a=l(a);if(!a)return k;var c=a.contents,f=a.index;if(d!=
f){for(;;){d=c.length;if(0>=d||" "!=c.charAt(d-1))break;c=c.substring(0,d-1)}c=e(!1,document.location,c,"?","&","#");c=e(k,document.location,c,"#",";");for(d=0;" "==c.charAt(d);)d++;0<d&&(c=c.substring(d));"http://"!=c.substring(0,7).toLowerCase()&&"https://"!=c.substring(0,8).toLowerCase()&&(c="http://"+c);b&&(a.contents=c,a=[a],c=b(a));c&&document.location.replace(c)}return k}function q(a){(a=l(a))&&0<a.index&&document.write(a.contents+"<nosc"+"ript>");return k}
function l(a){if(utmx_global_vd!=m)return utmx_global_vd[a]}function r(a){if((a=l(a))&&0<a.index)return a.contents}function s(a){if((a=l(a))&&0<=a.index)return a.index}function t(a){for(var d=0,b=0,a=""+a,e=a.length-1;0<=e;e--)if(b=parseInt(a.charCodeAt(e),0),d=(d<<6&268435455)+b+(b<<14),0!=(b=d&266338304))d^=b>>21;return d}var g;switch(e){case "section":g=q(b);break;case "url":g=o(b,i,f);break;case "variation":g=l(b);break;case "variation_content":g=r(b);break;case "variation_number":g=s(b);break;
case "combination":g=utmx_global_vd!=m?undefined:void 0;break;case "combination_string":g=utmx_global_vd!=m?undefined:void 0;break;case "domain_hash":g=t(b);break;case "live":g=false&&utmx_global_vd!=m;break;case "preview":g=false}return g}var utmx_global_vd = null;
(function(){if("undefined"!=typeof navigator.cookieEnabled&&!navigator.cookieEnabled)return!1;if(utmx("preview"))return k;var e;e=window._gaUserPrefs;var b="ioo";if(e=e&&e[b]&&e[b]())return!1;e=utmx("domain_hash",document.location);b=document.cookie;e="__utmx_k_"+e;var i=b.indexOf(e+"="),f=0;0<=i&&(f=b.indexOf(";",i),0>=f&&(f=b.length),f=parseInt(b.substring(i+e.length+1,f),10));b=new Date;i=b.getTime();b.setTime(i+2E3);f+=1;document.cookie=e+"="+f+";expires="+b.toGMTString();return 10<
f||0>document.cookie.indexOf(e+"="+f)?!1:k})()&&(utmx_global_vd={'Index_header-top_banner_1':{index:0,contents:''}});
